#!/bin/bash
#
# post-checkout
#
# descr: this is a script meant to be executed whenever doing 'git checkout <hash -or-branch>' to setup .gitignore and .gitattribute files
#
# notes: * this is ran after the contents of the repo are checked ouut

_post_checkout() {
    local PATH_THIS="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)/$(basename -- "${BASH_SOURCE[0]}")"
    local DIR_THIS="$(dirname -- "${PATH_THIS}")"
    local dir_repo="$(cd "${DIR_THIS}" && cd $(git rev-parse --show-toplevel) && echo ${PWD})" && [ "${dir_repo}" != '' ] || ! echo "ERROR: dir_repo=''" || return 1
    #### hardcoded vars
    local file_gitignore="${dir_repo}/.git-hooks/gitignore/gitignore-gen.bash"
    local file_gitattributes="${dir_repo}/.git-hooks/gitattributes/gitattributes-gen.bash"
    ## abort script if the git
    [ ${3} != '1' ] && return 0
    { [ -f "${file_gitignore}" ] || ! echo "WARNING: git hook script cannot find ${file_gitignore}"; } && "${file_gitignore}"
    { [ -f "${file_gitattributes}" ] || ! echo "WARNING: git hook script cannot find ${file_gitattributes}"; } && "${file_gitattributes}"
    return 0
}

_post_checkout "${@}" || exit "${?}"