#!/bin/bash
#
# description: adds line to add script directory to PATH

_scripts_init() {
    local script_path="${BASH_SOURCE[0]}"
	local script_dir="$(cd "$(dirname "${script_path}")"; pwd -P)"
	local bashrc="${HOME}/.bash_aliases"
	local line='PATH=${PATH}:'"${script_dir}/bash-sh"
	#### add line to bashrc to change PATH
	[ ! -f "${bashrc}" ] && { echo "NOTE: ${bashrc} does not exist, creating..."; touch "${bashrc}" && echo "source ${bash_aliases}" > "${bashrc}"; }
	grep -qF -- "${line}" "${bashrc}" || { echo >> "${bashrc}" && echo "${line}" >> "${bashrc}" && echo "NOTE: '${line}' added to '${bashrc}'"; } || return 1
}

_scripts_init "${@}" || exit "${?}"